import{a as B,S as v,i as m}from"./assets/vendor-xpOxgMII.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const M="54418567-38d23a8e17a003c539283c0a3",$="https://pixabay.com/api/",j=15;async function g(o,t){return(await B.get($,{params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:j}})).data}const d=document.querySelector(".gallery"),p=document.querySelector(".load-more"),h=document.querySelector(".loader"),A=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:n,largeImageURL:i,tags:e,likes:r,views:s,comments:b,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
          <ul class="gallery-img-info">
            <li>Likes<span class="js-info">${r}</span></li>
            <li>Views<span class="js-info">${s}</span></li>
            <li>Comments<span class="js-info">${b}</span></li>
            <li>Downloads<span class="js-info">${q}</span></li>
          </ul>
        </a>
      </li>
    `).join("");d.insertAdjacentHTML("beforeend",t),A.refresh()}function L(){d.innerHTML=""}function S(){h.classList.remove("hidden")}function w(){h.classList.add("hidden")}function H(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}function O(){let t=d.querySelector("li").getBoundingClientRect().height*2;window.scrollBy({top:t,behavior:"smooth"})}const E=document.querySelector(".form"),R=document.querySelector(".load-more");let l="",a=1,c=0;const _=15;E.addEventListener("submit",x);R.addEventListener("click",z);async function x(o){if(o.preventDefault(),l=o.currentTarget.elements["search-text"].value.trim(),!!l){a=1,c=0,L(),u(),S();try{const t=await g(l,a);if(c=t.totalHits,t.hits.length===0){f();return}y(t.hits),P()}catch(t){console.error(t),f()}finally{w(),E.reset()}}}async function z(){a+=1,S();try{const o=await g(l,a);y(o.hits),P(),O()}catch(o){console.error(o)}finally{w()}}function P(){a*_>=c?(u(),I()):H()}function f(){L(),u(),m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",close:!1,progressBar:!1,timeout:"3000",messageSize:"16"})}function I(){m.error({message:"We're sorry, but you've reached the end of search results.",position:"topRight",close:!1,progressBar:!1,timeout:"2000",messageSize:"16"})}
//# sourceMappingURL=index.js.map
